### ISSUE TITLE
Incompatibility problems with recent Python builds

### ISSUE THREAD

**Issue by jgagneastro** [fkiwy/Finder_charts#6]
I have had a few new errors to deal with before I could make the package work in a recent conda environment:

`Python 3.13.1 (ARM-version of conda 24.1.2 on Mac OS 15.2 Sequoia)`

```
astropy==7.0.0
astropy-iers-data==0.2024.12.9.0.36.21
astropy_healpix==1.0.3
astroquery==0.4.8.dev9474
autocommand==2.2.2
backports.tarfile==1.2.0
beautifulsoup4==4.13.0b2
certifi==2024.12.14
charset-normalizer==3.4.0
click==8.1.7
cloudpickle==3.1.0
contourpy==1.3.1
crc32c==2.7.1
cycler==0.12.1
dask==2024.12.0
donfig==0.8.1.post1
Finder_charts==1.1.0
fonttools==4.55.3
fsspec==2024.10.0
html5lib==1.1
idna==3.10
importlib_metadata==8.0.0
inflect==7.3.1
jaraco.classes==3.4.0
jaraco.collections==5.1.0
jaraco.context==5.3.0
jaraco.functools==4.0.1
jaraco.text==3.12.1
keyring==25.5.0
kiwisolver==1.4.7
locket==1.0.0
matplotlib==3.10.0
more-itertools==10.3.0
numcodecs==0.14.1
numpy==2.2.0
packaging==24.2
pandas @ file:///Users/runner/miniforge3/conda-bld/pandas_1726878437586/work
partd==1.4.2
pillow==11.0.0
platformdirs==4.2.2
pyerfa==2.0.1.5
pyparsing==3.2.0
python-dateutil==2.9.0.post0
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1706886791323/work
pyvo==1.6
PyYAML==6.0.2
reproject==0.14.1
requests==2.32.3
scipy==1.15.0rc1
setuptools==75.6.0
six==1.17.0
soupsieve==2.6
tomli==2.0.1
toolz==1.0.0
tqdm==4.67.1
typeguard==4.3.0
typing_extensions==4.12.2
tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1733235305708/work
urllib3==2.2.3
webencodings==0.5.1
wheel==0.43.0
zarr==3.0.0b3
zipp==3.19.2
```

I was initially getting the error:

```
  ~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/jonathan/Documents/Python/Python_Packages/Finder_charts/Finder_charts.py", line 518, in finder_charts
    job = Gaia.cone_search_async(coords, radius.to(u.deg))
TypeError: GaiaClass.cone_search_async() takes 2 positional arguments but 3 were given
```

And I fixed it by changing line 519 in Finder_charts.py:

```
# Get Gaia catalog entries if requested
        print(coords)
        if gaia_entries or gaia_pm_vectors:
            job = Gaia.cone_search_async(coords, radius.to(u.deg))
            gaia_results = job.get_results()
```

Into:

```
# Get Gaia catalog entries if requested
        print(coords)
        if gaia_entries or gaia_pm_vectors:
            job = Gaia.cone_search_async(coords, radius=radius.to(u.deg))
            gaia_results = job.get_results()
```

I then got the following error:

```
Traceback (most recent call last):
  File "/Users/jonathan/Documents/Python/Python_Library/moca_management/kiwy_fchart_radec.py", line 47, in <module>
    create_finder_charts(ra, dec, img_size=100, overlays=False, overlay_color='red', dss=True, twomass=True, spitzer=True, wise=True,
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                         ukidss=True, uhs=True, vhs=True, vvv=True, viking=True, ps1=True, decam=True, neowise=True, neowise_contrast=5,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                         gaia_images=True, gaia_entries=True, gaia_pm_vectors=True, gaia_pm_years=10, gaia_color='green', crosshair_type=Crosshair.CROSS_NO_CENTER,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                         chrono_order=True, object_info=True, directory=output_dir, cache=False, show_progress=True, timeout=300,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                         open_file=open_file, file_format=file_format, save_result_tables=False)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathan/Documents/Python/Python_Packages/Finder_charts/Finder_charts.py", line 1473, in create_finder_charts
    finder_charts(ra, dec)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/jonathan/Documents/Python/Python_Packages/Finder_charts/Finder_charts.py", line 1327, in finder_charts
    b, gaia_wcs, obs_coords = create_gaia_finder_chart(ra, dec, size=img_size, band='Bp', epoch=gaia_epoch)
                              ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathan/Documents/Python/Python_Packages/Finder_charts/Gaia_finder_chart.py", line 237, in create_gaia_finder_chart
    gaia_sources = get_gaia_sources(obs_coords, obs_time, radius=RADIUS)
  File "/Users/jonathan/Documents/Python/Python_Packages/Finder_charts/Gaia_finder_chart.py", line 158, in get_gaia_sources
    sources['gaia_id'].append(table_row['source_id'])
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'append'
```

And fixed it by replacing line 156 in Finder_charts/Gaia_finder_chart.py, from:

```
# add to sources
sources['gaia_id'].append(table_row['source_id'])
```

to:

```
# add to sources
sources['gaia_id'].append(table_row['SOURCE_ID'])
```

**Comment by fkiwy** [comment]
The fix for error #1 has already been applied on 06/15/24 with commit 0f435f6 (Fix Gaia source id).
The fix for error #2 has just been pushed to the main branch.
Thanks for reporting both errors.
